vim.cmd('command! ReloadConfig source $MYVIMRC')
vim.api.nvim_set_keymap('n', '<C-G>', ":lua require('search').open()<CR>", { noremap = true, silent = true })
require('config.lazy')
require('config.copilot')
require('config.lualine')
require('config.bufferline')
require('config.goto-preview')
require('config.telescope')
require('config.search')
require('config.treesitter')
require('config.colorizer')
require('config.lsp')
require('config.themer')
require('config.indentblankline')
